import type { NextApiRequest, NextApiResponse } from 'next/types'
import { ProductType } from 'src/types/apps/productTypes'

// Mock product data
const mockProducts: ProductType[] = [
  {
    codigo: 'PROD001',
    codigoBarra: '1234567890123',
    nombre: 'Arroz Blanco 1lb',
    descripcion: 'Arroz blanco de primera calidad',
    area: 'GRANOS',
    iDArea: 1,
    grupoId: 'GRP001',
    departamento: 'ALIMENTOS',
    ultCompra: '2024-01-15',
    precio1: 85.0,
    precio2: 80.0,
    precio3: 75.0,
    precio4: 70.0,
    precio5: 65.0,
    costo: 50.0,
    existenciaAlmacen1: 100,
    existenciaAlmacen2: 50,
    existenciaAlmacen3: 25,
    existenciaAlmacen4: 0,
    existenciaAlmacen5: 0,
    existenciaAlmacen6: 0,
    existenciaAlmacen7: 0,
    unidad: 'LB',
    empaque: 'BOLSA',
    impuesto: 18,
    factor: 1,
    iSC: 0,
    aDV: 0,
    descuento: 0,
    tipoImpuesto: 'ITBIS',
    apartado: 0,
    promocion: false,
    status: 'A',
    imagenes: [],
    visibleTienda: true,
    esServicio: false,
  },
  {
    codigo: 'PROD002',
    codigoBarra: '1234567890124',
    nombre: 'Leche Entera 1 Litro',
    descripcion: 'Leche entera pasteurizada',
    area: 'LACTEOS',
    iDArea: 2,
    grupoId: 'GRP002',
    departamento: 'REFRIGERADOS',
    ultCompra: '2024-01-16',
    precio1: 95.0,
    precio2: 90.0,
    precio3: 85.0,
    precio4: 80.0,
    precio5: 75.0,
    costo: 60.0,
    existenciaAlmacen1: 75,
    existenciaAlmacen2: 30,
    existenciaAlmacen3: 15,
    existenciaAlmacen4: 0,
    existenciaAlmacen5: 0,
    existenciaAlmacen6: 0,
    existenciaAlmacen7: 0,
    unidad: 'L',
    empaque: 'CARTON',
    impuesto: 18,
    factor: 1,
    iSC: 0,
    aDV: 0,
    descuento: 0,
    tipoImpuesto: 'ITBIS',
    apartado: 0,
    promocion: false,
    status: 'A',
    imagenes: [],
    visibleTienda: true,
    esServicio: false,
  },
  {
    codigo: 'PROD003',
    codigoBarra: '1234567890125',
    nombre: 'Pan de Molde Integral',
    descripcion: 'Pan de molde integral fortificado',
    area: 'PANADERIA',
    iDArea: 3,
    grupoId: 'GRP003',
    departamento: 'PANADERIA',
    ultCompra: '2024-01-17',
    precio1: 125.0,
    precio2: 120.0,
    precio3: 115.0,
    precio4: 110.0,
    precio5: 105.0,
    costo: 80.0,
    existenciaAlmacen1: 50,
    existenciaAlmacen2: 25,
    existenciaAlmacen3: 10,
    existenciaAlmacen4: 0,
    existenciaAlmacen5: 0,
    existenciaAlmacen6: 0,
    existenciaAlmacen7: 0,
    unidad: 'UN',
    empaque: 'BOLSA',
    impuesto: 18,
    factor: 1,
    iSC: 0,
    aDV: 0,
    descuento: 0,
    tipoImpuesto: 'ITBIS',
    apartado: 0,
    promocion: true,
    status: 'A',
    imagenes: [],
    visibleTienda: true,
    esServicio: false,
  },
  {
    codigo: 'PROD004',
    codigoBarra: '1234567890126',
    nombre: 'Agua Mineral 500ml',
    descripcion: 'Agua mineral natural',
    area: 'BEBIDAS',
    iDArea: 4,
    grupoId: 'GRP004',
    departamento: 'BEBIDAS',
    ultCompra: '2024-01-18',
    precio1: 35.0,
    precio2: 32.0,
    precio3: 30.0,
    precio4: 28.0,
    precio5: 25.0,
    costo: 20.0,
    existenciaAlmacen1: 200,
    existenciaAlmacen2: 100,
    existenciaAlmacen3: 50,
    existenciaAlmacen4: 25,
    existenciaAlmacen5: 0,
    existenciaAlmacen6: 0,
    existenciaAlmacen7: 0,
    unidad: 'UN',
    empaque: 'BOTELLA',
    impuesto: 18,
    factor: 1,
    iSC: 0,
    aDV: 0,
    descuento: 0,
    tipoImpuesto: 'ITBIS',
    apartado: 0,
    promocion: false,
    status: 'A',
    imagenes: [],
    visibleTienda: true,
    esServicio: false,
  },
  {
    codigo: 'PROD005',
    codigoBarra: '1234567890127',
    nombre: 'Jabón de Manos Antibacterial',
    descripcion: 'Jabón líquido antibacterial para manos',
    area: 'LIMPIEZA',
    iDArea: 5,
    grupoId: 'GRP005',
    departamento: 'CUIDADO_PERSONAL',
    ultCompra: '2024-01-19',
    precio1: 165.0,
    precio2: 160.0,
    precio3: 155.0,
    precio4: 150.0,
    precio5: 145.0,
    costo: 110.0,
    existenciaAlmacen1: 40,
    existenciaAlmacen2: 20,
    existenciaAlmacen3: 10,
    existenciaAlmacen4: 5,
    existenciaAlmacen5: 0,
    existenciaAlmacen6: 0,
    existenciaAlmacen7: 0,
    unidad: 'UN',
    empaque: 'BOTELLA',
    impuesto: 18,
    factor: 1,
    iSC: 0,
    aDV: 0,
    descuento: 0,
    tipoImpuesto: 'ITBIS',
    apartado: 0,
    promocion: false,
    status: 'A',
    imagenes: [],
    visibleTienda: true,
    esServicio: false,
  },
]

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'GET') {
    try {
      // Simulate API delay
      setTimeout(() => {
        res.status(200).json({
          success: true,
          products: mockProducts,
          total: mockProducts.length,
        })
      }, 500)
    } catch (error) {
      res.status(500).json({
        success: false,
        message: 'Error fetching products',
        error: error,
      })
    }
  } else {
    res.setHeader('Allow', ['GET'])
    res.status(405).end(`Method ${req.method} Not Allowed`)
  }
}
